---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "bun"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/dashboard"
      - "/packages/shared-types"
    schedule:
      interval: "daily"
    groups:
      typescript-eslint:
        patterns:
          - "*typescript-eslint*"
      commitlint:
        patterns:
          - "commitlint*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"

      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "eslint*"
          - "@eslint/*"
          - "*typescript-eslint*"
          - "commitlint*"

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "docker"
    directories:
      - "/apps/api"
      - "/apps/dashboard"
      - "/apps/indexer"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "cargo"
    directory: "/apps/indexer"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

