---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/dashboard"
      - "/packages/shared-types"
    schedule:
      interval: "daily"
    groups:
      linters:
        patterns:
          - "*eslint*"
          - "commitlint*"

      monorepo-dependencies:
        group-by: dependency-name
        exclude-patterns:
          - "*eslint*"
          - "commitlint/*"

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "docker"
    directories:
      - "/apps/api"
      - "/apps/dashboard"
      - "/apps/indexer"
    schedule:
      interval: "daily"
    groups:

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    groups:

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "cargo"
    directory: "/apps/indexer"
    schedule:
      interval: "daily"
    groups:

      security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

