/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your Sui client by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")` and passing it as the `overrides` option.
 */

const mainnetResolution = {
  packages: {},
  types: {},
};
const testnetResolution = {
  packages: {
    '@evefrontier/world': '0xd2fd1224f881e7a705dbc211888af11655c315f2ee0f03fe680fc3176e6e4780',
  },
  types: {},
};

export function getMvrCache(network: 'mainnet' | 'testnet') {
  return network === 'mainnet' ? mainnetResolution : testnetResolution;
}
