name: Deploy to Cloud Run

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  VPC_CONNECTOR: ${{ secrets.GCP_VPC_CONNECTOR }}
  REPO: sentinel-repo
  DB_NAME: sentinel-db
  DB_URN: sentinel
  EVE_PACKAGE_ID_STILLNESS: '0x28b497559d65ab320d9da4613bf2498d5946b2c0ae3597ccfda3072ce127448c'
  EVE_PACKAGE_ID_UTOPIA: '0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75'
  SUI_NETWORK: testnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Images
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/api:latest -f apps/api/Dockerfile .
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/dashboard:latest -f apps/dashboard/Dockerfile .
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/indexer:latest -f apps/indexer/Dockerfile .

      - name: Push Images
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/api:latest
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/dashboard:latest
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/indexer:latest

      - name: Deploy API
        run: |
          gcloud run deploy api \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/api:latest \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT }} \
            --vpc-connector=${{ secrets.GCP_VPC_CONNECTOR }} \
            --add-cloudsql-instances ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ env.DB_NAME }} \
            --set-env-vars DATABASE_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@/${{ env.DB_URN }}?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ env.DB_NAME }} \
            --allow-unauthenticated \
            --port 3001

      - name: Deploy Indexer
        run: |
          EVE_PACKAGE_ID="${{ env.EVE_PACKAGE_ID_STILLNESS }},${{ env.EVE_PACKAGE_ID_UTOPIA }}"
          gcloud run deploy indexer \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/indexer:latest \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT }} \
            --vpc-connector=${{ secrets.GCP_VPC_CONNECTOR }} \
            --add-cloudsql-instances ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ env.DB_NAME }} \
            --set-env-vars=^__^DATABASE_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@/${{ env.DB_URN }}?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ env.DB_NAME }}__SUI_RPC_URL=https://fullnode.${{ env.SUI_NETWORK }}.sui.io__EVE_PACKAGE_ID=${EVE_PACKAGE_ID} \
            --no-cpu-throttling \
            --min-instances 1 \
            --allow-unauthenticated \
            --port 8080

      - name: Deploy Dashboard
        run: |
          API_URL=$(gcloud run services describe api --region ${{ secrets.GCP_REGION }} --format="value(status.url)")
          echo "API deployed at $API_URL"

          gcloud run deploy dashboard \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/dashboard:latest \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT }} \
            --vpc-connector=${{ secrets.GCP_VPC_CONNECTOR }} \
            --set-env-vars API_PROXY_URL=$API_URL,GRAPHQL_PROXY_URL=https://graphql.${{ env.SUI_NETWORK }}.sui.io \
            --allow-unauthenticated \
            --port 5173
